import type { openapi_reference, openapi_schema_object } from './types.ts';

export function ref(ref: string): string {
	return ref.split('/').pop()?.replaceAll('%20', '')?.replaceAll(' ', '') ??
		'unknown';
}

function get_enum(vals?: unknown[]): string | undefined {
	return vals?.length
		? vals.map((v) => JSON.stringify(v)).join(' | ')
		: undefined;
}

function composite(schema: openapi_schema_object): string[] {
	const pick = (k: 'oneOf' | 'anyOf' | 'allOf', sep: string) =>
		schema[k]?.length
			? `(${schema[k].map(get_type).join(` ${sep} `)})`
			: undefined;
	return [
		pick('oneOf', '|'),
		pick('anyOf', '|'),
		pick('allOf', '&'),
	].filter(Boolean) as string[];
}

export function get_type(
	item: openapi_reference | openapi_schema_object,
): string {
	if ('$ref' in item) return ref(item.$ref);

	let base = get_enum(item.enum) ??
		(item.type === 'string'
			? 'string'
			: item.type === 'number' || item.type === 'integer'
			? 'number'
			: item.type === 'boolean'
			? 'boolean'
			: item.type === 'null'
			? 'null'
			: item.type === 'array'
			? (() => {
				if (!item.items) return 'unknown[]';
				const items = Array.isArray(item.items)
					? item.items.map(get_type).join(' | ')
					: get_type(item.items);
				return (item as openapi_schema_object).nullable
					? `(${items})[] | null`
					: `(${items})[]`;
			})()
			: item.type === 'object'
			? (() => {
				if (item.properties) {
					const props = Object.entries(item.properties)
						.map(
							([k, v]) =>
								`  ${k}${(v as openapi_schema_object).nullable ? '?' : ''}: ${
									get_type(v)
								};`,
						)
						.join('\n');
					return `{\n${props}\n}`;
				}

				if (
					item.additionalProperties &&
					typeof item.additionalProperties === 'object'
				) {
					const value = get_type(item.additionalProperties);
					return `Record<string, ${value}>`;
				}

				return 'Record<string, unknown>';
			})()
			: undefined) ??
		'unknown';

	const comps = composite(item);

	if (comps.length) {
		base = base === 'unknown'
			? comps.join(' & ')
			: [base, ...comps].join(' & ');
	}

	if ((item as openapi_schema_object).nullable && item.type !== 'array') {
		base = `${base} | null`;
	}

	return base;
}

function handle_schema(
	name: string,
	schema: openapi_schema_object,
): string {
	const doc_comment = `/**\n  * @description ${
		schema.description ?? schema.title ?? name
	}\n*/\n`;

	name = name.replaceAll(' ', '').replaceAll('%20', '');

	if (schema.type === 'object' && schema.properties) {
		const body = Object.entries(schema.properties)
			.map(([property_name, property_schema]) => {
				const property_schema_object = property_schema as openapi_schema_object;
				const is_nullable = property_schema_object.nullable;
				return `  /** @description ${
					property_schema_object.description || property_schema_object.title ||
					property_name
				} */\n  ${property_name}${is_nullable ? '?' : ''}: ${
					get_type(property_schema)
				};`;
			})
			.join('\n');
		const comps = composite(schema);
		if (comps.length) {
			return `${doc_comment}export type ${name} = {\n${body}\n} & ${
				comps.join(' & ')
			}${schema.nullable ? ' | null' : ''}`;
		}
		return `${doc_comment}export interface ${name} {\n${body}\n}`;
	}

	return `${doc_comment}export type ${name} = ${get_type(schema)}`;
}

export function generate_types(
	schema: Record<string, openapi_schema_object>,
): string {
	let output = `// autogenerated by @jersey/openapi\n\n`;

	for (const [name, value] of Object.entries(schema)) {
		output += handle_schema(name, value) + '\n\n';
	}

	return output + '\n\n';
}
