// this file was autogenerated by @jersey/openapi

import type { operations } from './schema.ts';
export type routes =
	| {
		method: 'get';
		path: `/`;
		parts: 1;
		params: undefined;
		response: operations['root_root']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/users/@me`;
		parts: 2;
		params: undefined;
		response: operations['fetch_self_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/users/${string}`;
		parts: 2;
		params: undefined;
		response: operations['fetch_user_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/users/{target}';
		parts: 2;
		params: undefined;
		response: operations['fetch_user_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: `/users/${string}`;
		parts: 2;
		params: operations['edit_user_edit']['requestBody']['content'][
			'application/json'
		];
		response: operations['edit_user_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/users/{target}';
		parts: 2;
		params: operations['edit_user_edit']['requestBody']['content'][
			'application/json'
		];
		response: operations['edit_user_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/users/${string}/flags`;
		parts: 3;
		params: undefined;
		response:
			operations['fetch_user_flags_fetch_user_flags']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'get';
		path: '-/users/{target}/flags';
		parts: 3;
		params: undefined;
		response:
			operations['fetch_user_flags_fetch_user_flags']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'patch';
		path: `/users/@me/username`;
		parts: 3;
		params:
			operations['change_username_change_username']['requestBody']['content'][
				'application/json'
			];
		response: operations['change_username_change_username']['responses']['200'][
			'content'
		]['application/json'];
	}
	| {
		method: 'get';
		path: `/users/${string}/default_avatar`;
		parts: 3;
		params: undefined;
		response:
			operations['get_default_avatar_default_avatar']['responses']['200'][
				'content'
			]['image/png'];
	}
	| {
		method: 'get';
		path: '-/users/{target}/default_avatar';
		parts: 3;
		params: undefined;
		response:
			operations['get_default_avatar_default_avatar']['responses']['200'][
				'content'
			]['image/png'];
	}
	| {
		method: 'get';
		path: `/users/${string}/profile`;
		parts: 3;
		params: undefined;
		response:
			operations['fetch_profile_profile']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/users/{target}/profile';
		parts: 3;
		params: undefined;
		response:
			operations['fetch_profile_profile']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/users/dms`;
		parts: 2;
		params: undefined;
		response:
			operations['fetch_dms_direct_messages']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/users/${string}/dm`;
		parts: 3;
		params: undefined;
		response: operations['open_dm_open_dm']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/users/{target}/dm';
		parts: 3;
		params: undefined;
		response: operations['open_dm_open_dm']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/users/${string}/mutual`;
		parts: 3;
		params: undefined;
		response: operations['find_mutual_mutual']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/users/{target}/mutual';
		parts: 3;
		params: undefined;
		response: operations['find_mutual_mutual']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: `/users/${string}/friend`;
		parts: 3;
		params: undefined;
		response: operations['add_friend_add']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: '-/users/{target}/friend';
		parts: 3;
		params: undefined;
		response: operations['add_friend_add']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/users/${string}/friend`;
		parts: 3;
		params: undefined;
		response: operations['remove_friend_remove']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: '-/users/{target}/friend';
		parts: 3;
		params: undefined;
		response: operations['remove_friend_remove']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: `/users/${string}/block`;
		parts: 3;
		params: undefined;
		response: operations['block_user_block']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: '-/users/{target}/block';
		parts: 3;
		params: undefined;
		response: operations['block_user_block']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/users/${string}/block`;
		parts: 3;
		params: undefined;
		response: operations['unblock_user_unblock']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: '-/users/{target}/block';
		parts: 3;
		params: undefined;
		response: operations['unblock_user_unblock']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: `/users/friend`;
		parts: 2;
		params:
			operations['send_friend_request_send_friend_request']['requestBody'][
				'content'
			]['application/json'];
		response:
			operations['send_friend_request_send_friend_request']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'post';
		path: `/bots/create`;
		parts: 2;
		params: operations['create_create_bot']['requestBody']['content'][
			'application/json'
		];
		response: operations['create_create_bot']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/bots/${string}/invite`;
		parts: 3;
		params: undefined;
		response: operations['fetch_public_fetch_public_bot']['responses']['200'][
			'content'
		]['application/json'];
	}
	| {
		method: 'get';
		path: '-/bots/{target}/invite';
		parts: 3;
		params: undefined;
		response: operations['fetch_public_fetch_public_bot']['responses']['200'][
			'content'
		]['application/json'];
	}
	| {
		method: 'post';
		path: `/bots/${string}/invite`;
		parts: 3;
		params: operations['invite_invite_bot']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'post';
		path: '-/bots/{target}/invite';
		parts: 3;
		params: operations['invite_invite_bot']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'get';
		path: `/bots/${string}`;
		parts: 2;
		params: undefined;
		response: operations['fetch_fetch_bot']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/bots/{bot}';
		parts: 2;
		params: undefined;
		response: operations['fetch_fetch_bot']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/bots/@me`;
		parts: 2;
		params: undefined;
		response:
			operations['fetch_owned_fetch_owned_bots']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'delete';
		path: `/bots/${string}`;
		parts: 2;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/bots/{target}';
		parts: 2;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'patch';
		path: `/bots/${string}`;
		parts: 2;
		params:
			operations['edit_edit_bot']['requestBody']['content']['application/json'];
		response: operations['edit_edit_bot']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/bots/{target}';
		parts: 2;
		params:
			operations['edit_edit_bot']['requestBody']['content']['application/json'];
		response: operations['edit_edit_bot']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: `/channels/${string}/ack/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/channels/{target}/ack/{message}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/channels/${string}`;
		parts: 2;
		params: undefined;
		response: operations['channel_fetch_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{target}';
		parts: 2;
		params: undefined;
		response: operations['channel_fetch_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/channels/${string}`;
		parts: 2;
		params: operations['channel_delete_delete']['parameters']['query'];
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{target}';
		parts: 2;
		params: operations['channel_delete_delete']['parameters']['query'];
		response: undefined;
	}
	| {
		method: 'patch';
		path: `/channels/${string}`;
		parts: 2;
		params: operations['channel_edit_edit']['requestBody']['content'][
			'application/json'
		];
		response: operations['channel_edit_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/channels/{target}';
		parts: 2;
		params: operations['channel_edit_edit']['requestBody']['content'][
			'application/json'
		];
		response: operations['channel_edit_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}/members`;
		parts: 3;
		params: undefined;
		response:
			operations['members_fetch_fetch_members']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/channels/{target}/members';
		parts: 3;
		params: undefined;
		response:
			operations['members_fetch_fetch_members']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: `/channels/${string}/invites`;
		parts: 3;
		params: undefined;
		response:
			operations['invite_create_create_invite']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: '-/channels/{target}/invites';
		parts: 3;
		params: undefined;
		response:
			operations['invite_create_create_invite']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/channels/${string}/messages`;
		parts: 3;
		params: operations['message_query_query']['parameters']['query'];
		response: operations['message_query_query']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{target}/messages';
		parts: 3;
		params: operations['message_query_query']['parameters']['query'];
		response: operations['message_query_query']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: `/channels/${string}/messages`;
		parts: 3;
		params: operations['message_send_message_send']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['message_send_message_send']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: '-/channels/{target}/messages';
		parts: 3;
		params: operations['message_send_message_send']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['message_send_message_send']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: `/channels/${string}/search`;
		parts: 3;
		params: operations['message_search_search']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['message_search_search']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: '-/channels/{target}/search';
		parts: 3;
		params: operations['message_search_search']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['message_search_search']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: `/channels/${string}/messages/${string}/pin`;
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: '-/channels/{target}/messages/{msg}/pin';
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/messages/${string}/pin`;
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{target}/messages/{msg}/pin';
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/channels/${string}/messages/${string}`;
		parts: 4;
		params: undefined;
		response: operations['message_fetch_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{target}/messages/{msg}';
		parts: 4;
		params: undefined;
		response: operations['message_fetch_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/channels/${string}/messages/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{target}/messages/{msg}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'patch';
		path: `/channels/${string}/messages/${string}`;
		parts: 4;
		params: operations['message_edit_edit']['requestBody']['content'][
			'application/json'
		];
		response: operations['message_edit_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/channels/{target}/messages/{msg}';
		parts: 4;
		params: operations['message_edit_edit']['requestBody']['content'][
			'application/json'
		];
		response: operations['message_edit_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/channels/${string}/messages/bulk`;
		parts: 4;
		params:
			operations['message_bulk_delete_bulk_delete_messages']['requestBody'][
				'content'
			]['application/json'];
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{target}/messages/bulk';
		parts: 4;
		params:
			operations['message_bulk_delete_bulk_delete_messages']['requestBody'][
				'content'
			]['application/json'];
		response: undefined;
	}
	| {
		method: 'post';
		path: `/channels/create`;
		parts: 2;
		params: operations['group_create_create_group']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['group_create_create_group']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'put';
		path: `/channels/${string}/recipients/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/channels/{group_id}/recipients/{member_id}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/recipients/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{target}/recipients/{member}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/channels/${string}/join_call`;
		parts: 3;
		params: undefined;
		response: operations['voice_join_call']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/channels/{target}/join_call';
		parts: 3;
		params: undefined;
		response: operations['voice_join_call']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: `/channels/${string}/permissions/${string}`;
		parts: 4;
		params: operations['permissions_set_set_role_permissions']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['permissions_set_set_role_permissions']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'put';
		path: '-/channels/{target}/permissions/{role_id}';
		parts: 4;
		params: operations['permissions_set_set_role_permissions']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['permissions_set_set_role_permissions']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'put';
		path: `/channels/${string}/permissions/default`;
		parts: 4;
		params: operations['permissions_set_default_set_default_permissions'][
			'requestBody'
		]['content']['application/json'];
		response: operations['permissions_set_default_set_default_permissions'][
			'responses'
		]['200']['content']['application/json'];
	}
	| {
		method: 'put';
		path: '-/channels/{target}/permissions/default';
		parts: 4;
		params: operations['permissions_set_default_set_default_permissions'][
			'requestBody'
		]['content']['application/json'];
		response: operations['permissions_set_default_set_default_permissions'][
			'responses'
		]['200']['content']['application/json'];
	}
	| {
		method: 'put';
		path: `/channels/${string}/messages/${string}/reactions/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/channels/{target}/messages/{msg}/reactions/{emoji}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/messages/${string}/reactions/${string}`;
		parts: 6;
		params:
			operations['message_unreact_unreact_message']['parameters']['query'];
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{target}/messages/{msg}/reactions/{emoji}';
		parts: 6;
		params:
			operations['message_unreact_unreact_message']['parameters']['query'];
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/messages/${string}/reactions`;
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{target}/messages/{msg}/reactions';
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/channels/${string}/webhooks`;
		parts: 3;
		params:
			operations['webhook_create_create_webhook']['requestBody']['content'][
				'application/json'
			];
		response: operations['webhook_create_create_webhook']['responses']['200'][
			'content'
		]['application/json'];
	}
	| {
		method: 'post';
		path: '-/channels/{target}/webhooks';
		parts: 3;
		params:
			operations['webhook_create_create_webhook']['requestBody']['content'][
				'application/json'
			];
		response: operations['webhook_create_create_webhook']['responses']['200'][
			'content'
		]['application/json'];
	}
	| {
		method: 'get';
		path: `/channels/${string}/webhooks`;
		parts: 3;
		params: undefined;
		response:
			operations['webhook_fetch_all_fetch_webhooks']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'get';
		path: '-/channels/{channel_id}/webhooks';
		parts: 3;
		params: undefined;
		response:
			operations['webhook_fetch_all_fetch_webhooks']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'post';
		path: `/servers/create`;
		parts: 2;
		params: operations['server_create_create_server']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['server_create_create_server']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/servers/${string}`;
		parts: 2;
		params: operations['server_fetch_fetch']['parameters']['query'];
		response: operations['server_fetch_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{target}';
		parts: 2;
		params: operations['server_fetch_fetch']['parameters']['query'];
		response: operations['server_fetch_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/servers/${string}`;
		parts: 2;
		params: operations['server_delete_delete']['parameters']['query'];
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/servers/{target}';
		parts: 2;
		params: operations['server_delete_delete']['parameters']['query'];
		response: undefined;
	}
	| {
		method: 'patch';
		path: `/servers/${string}`;
		parts: 2;
		params: operations['server_edit_edit']['requestBody']['content'][
			'application/json'
		];
		response: operations['server_edit_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/servers/{target}';
		parts: 2;
		params: operations['server_edit_edit']['requestBody']['content'][
			'application/json'
		];
		response: operations['server_edit_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: `/servers/${string}/ack`;
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/servers/{target}/ack';
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/servers/${string}/channels`;
		parts: 3;
		params: operations['channel_create_create_server_channel']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['channel_create_create_server_channel']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'post';
		path: '-/servers/{server}/channels';
		parts: 3;
		params: operations['channel_create_create_server_channel']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['channel_create_create_server_channel']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'get';
		path: `/servers/${string}/members`;
		parts: 3;
		params: operations['member_fetch_all_fetch_all']['parameters']['query'];
		response:
			operations['member_fetch_all_fetch_all']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/servers/{target}/members';
		parts: 3;
		params: operations['member_fetch_all_fetch_all']['parameters']['query'];
		response:
			operations['member_fetch_all_fetch_all']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/servers/${string}/members/${string}`;
		parts: 4;
		params: operations['member_fetch_fetch']['parameters']['query'];
		response: operations['member_fetch_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{target}/members/{member}';
		parts: 4;
		params: operations['member_fetch_fetch']['parameters']['query'];
		response: operations['member_fetch_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/members/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/servers/{target}/members/{member}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'patch';
		path: `/servers/${string}/members/${string}`;
		parts: 4;
		params: operations['member_edit_edit']['requestBody']['content'][
			'application/json'
		];
		response: operations['member_edit_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/servers/{server}/members/{member}';
		parts: 4;
		params: operations['member_edit_edit']['requestBody']['content'][
			'application/json'
		];
		response: operations['member_edit_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/servers/${string}/members_experimental_query`;
		parts: 3;
		params: operations['member_experimental_query_member_experimental_query'][
			'parameters'
		]['query'];
		response: operations['member_experimental_query_member_experimental_query'][
			'responses'
		]['200']['content']['application/json'];
	}
	| {
		method: 'get';
		path: '-/servers/{target}/members_experimental_query';
		parts: 3;
		params: operations['member_experimental_query_member_experimental_query'][
			'parameters'
		]['query'];
		response: operations['member_experimental_query_member_experimental_query'][
			'responses'
		]['200']['content']['application/json'];
	}
	| {
		method: 'put';
		path: `/servers/${string}/bans/${string}`;
		parts: 4;
		params: operations['ban_create_ban']['requestBody']['content'][
			'application/json'
		];
		response: operations['ban_create_ban']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: '-/servers/{server}/bans/{target}';
		parts: 4;
		params: operations['ban_create_ban']['requestBody']['content'][
			'application/json'
		];
		response: operations['ban_create_ban']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/bans/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/servers/{server}/bans/{target}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/servers/${string}/bans`;
		parts: 3;
		params: undefined;
		response: operations['ban_list_list']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{target}/bans';
		parts: 3;
		params: undefined;
		response: operations['ban_list_list']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/servers/${string}/invites`;
		parts: 3;
		params: undefined;
		response:
			operations['invites_fetch_invites']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/servers/{target}/invites';
		parts: 3;
		params: undefined;
		response:
			operations['invites_fetch_invites']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: `/servers/${string}/roles`;
		parts: 3;
		params: operations['roles_create_create']['requestBody']['content'][
			'application/json'
		];
		response: operations['roles_create_create']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/servers/{target}/roles';
		parts: 3;
		params: operations['roles_create_create']['requestBody']['content'][
			'application/json'
		];
		response: operations['roles_create_create']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/servers/${string}/roles/${string}`;
		parts: 4;
		params: undefined;
		response: operations['roles_fetch_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{target}/roles/{role_id}';
		parts: 4;
		params: undefined;
		response: operations['roles_fetch_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/roles/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/servers/{target}/roles/{role_id}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'patch';
		path: `/servers/${string}/roles/${string}`;
		parts: 4;
		params: operations['roles_edit_edit']['requestBody']['content'][
			'application/json'
		];
		response: operations['roles_edit_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/servers/{target}/roles/{role_id}';
		parts: 4;
		params: operations['roles_edit_edit']['requestBody']['content'][
			'application/json'
		];
		response: operations['roles_edit_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: `/servers/${string}/permissions/${string}`;
		parts: 4;
		params: operations['permissions_set_set_role_permission']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['permissions_set_set_role_permission']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'put';
		path: '-/servers/{target}/permissions/{role_id}';
		parts: 4;
		params: operations['permissions_set_set_role_permission']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['permissions_set_set_role_permission']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'put';
		path: `/servers/${string}/permissions/default`;
		parts: 4;
		params:
			operations['permissions_set_default_set_default_permissions_servers'][
				'requestBody'
			]['content']['application/json'];
		response:
			operations['permissions_set_default_set_default_permissions_servers'][
				'responses'
			]['200']['content']['application/json'];
	}
	| {
		method: 'put';
		path: '-/servers/{target}/permissions/default';
		parts: 4;
		params:
			operations['permissions_set_default_set_default_permissions_servers'][
				'requestBody'
			]['content']['application/json'];
		response:
			operations['permissions_set_default_set_default_permissions_servers'][
				'responses'
			]['200']['content']['application/json'];
	}
	| {
		method: 'get';
		path: `/servers/${string}/emojis`;
		parts: 3;
		params: undefined;
		response:
			operations['emoji_list_list_emoji']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/servers/{target}/emojis';
		parts: 3;
		params: undefined;
		response:
			operations['emoji_list_list_emoji']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/invites/${string}`;
		parts: 2;
		params: undefined;
		response: operations['invite_fetch_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/invites/{target}';
		parts: 2;
		params: undefined;
		response: operations['invite_fetch_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: `/invites/${string}`;
		parts: 2;
		params: undefined;
		response: operations['invite_join_join']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/invites/{target}';
		parts: 2;
		params: undefined;
		response: operations['invite_join_join']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/invites/${string}`;
		parts: 2;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/invites/{target}';
		parts: 2;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: `/custom/emoji/${string}`;
		parts: 3;
		params: operations['emoji_create_create_emoji']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['emoji_create_create_emoji']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'put';
		path: '-/custom/emoji/{id}';
		parts: 3;
		params: operations['emoji_create_create_emoji']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['emoji_create_create_emoji']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/custom/emoji/${string}`;
		parts: 3;
		params: undefined;
		response:
			operations['emoji_fetch_fetch_emoji']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/custom/emoji/{emoji_id}';
		parts: 3;
		params: undefined;
		response:
			operations['emoji_fetch_fetch_emoji']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'delete';
		path: `/custom/emoji/${string}`;
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/custom/emoji/{emoji_id}';
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/safety/report`;
		parts: 2;
		params:
			operations['report_content_report_content']['requestBody']['content'][
				'application/json'
			];
		response: undefined;
	}
	| {
		method: 'post';
		path: `/auth/account/create`;
		parts: 3;
		params:
			operations['create_account_create_account']['requestBody']['content'][
				'application/json'
			];
		response: undefined;
	}
	| {
		method: 'post';
		path: `/auth/account/reverify`;
		parts: 3;
		params:
			operations['resend_verification_resend_verification']['requestBody'][
				'content'
			]['application/json'];
		response: undefined;
	}
	| {
		method: 'put';
		path: `/auth/account/delete`;
		parts: 3;
		params:
			operations['confirm_deletion_confirm_deletion']['requestBody']['content'][
				'application/json'
			];
		response: undefined;
	}
	| {
		method: 'post';
		path: `/auth/account/delete`;
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/auth/account/`;
		parts: 3;
		params: undefined;
		response:
			operations['fetch_account_fetch_account']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: `/auth/account/disable`;
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'patch';
		path: `/auth/account/change/password`;
		parts: 4;
		params:
			operations['change_password_change_password']['requestBody']['content'][
				'application/json'
			];
		response: undefined;
	}
	| {
		method: 'patch';
		path: `/auth/account/change/email`;
		parts: 4;
		params: operations['change_email_change_email']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'post';
		path: `/auth/account/verify/${string}`;
		parts: 4;
		params: undefined;
		response:
			operations['verify_email_verify_email']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: '-/auth/account/verify/{code}';
		parts: 4;
		params: undefined;
		response:
			operations['verify_email_verify_email']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: `/auth/account/reset_password`;
		parts: 3;
		params:
			operations['send_password_reset_send_password_reset']['requestBody'][
				'content'
			]['application/json'];
		response: undefined;
	}
	| {
		method: 'patch';
		path: `/auth/account/reset_password`;
		parts: 3;
		params:
			operations['password_reset_password_reset']['requestBody']['content'][
				'application/json'
			];
		response: undefined;
	}
	| {
		method: 'post';
		path: `/auth/session/login`;
		parts: 3;
		params:
			operations['login_login']['requestBody']['content']['application/json'];
		response: operations['login_login']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: `/auth/session/logout`;
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/auth/session/all`;
		parts: 3;
		params: undefined;
		response: operations['fetch_all_fetch_all']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/auth/session/all`;
		parts: 3;
		params: operations['revoke_all_revoke_all']['parameters']['query'];
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/auth/session/${string}`;
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/auth/session/{id}';
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'patch';
		path: `/auth/session/${string}`;
		parts: 3;
		params:
			operations['edit_edit']['requestBody']['content']['application/json'];
		response: operations['edit_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/auth/session/{id}';
		parts: 3;
		params:
			operations['edit_edit']['requestBody']['content']['application/json'];
		response: operations['edit_edit']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: `/auth/mfa/ticket`;
		parts: 3;
		params: operations['create_ticket_create_ticket']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['create_ticket_create_ticket']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/auth/mfa/`;
		parts: 3;
		params: undefined;
		response:
			operations['fetch_status_fetch_status']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: `/auth/mfa/recovery`;
		parts: 3;
		params: undefined;
		response: operations['fetch_recovery_fetch_recovery']['responses']['200'][
			'content'
		]['application/json'];
	}
	| {
		method: 'patch';
		path: `/auth/mfa/recovery`;
		parts: 3;
		params: undefined;
		response:
			operations['generate_recovery_generate_recovery']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'get';
		path: `/auth/mfa/methods`;
		parts: 3;
		params: undefined;
		response: operations['get_mfa_methods_get_mfa_methods']['responses']['200'][
			'content'
		]['application/json'];
	}
	| {
		method: 'put';
		path: `/auth/mfa/totp`;
		parts: 3;
		params: operations['totp_enable_totp_enable']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'post';
		path: `/auth/mfa/totp`;
		parts: 3;
		params: undefined;
		response:
			operations['totp_generate_secret_totp_generate_secret']['responses'][
				'200'
			]['content']['application/json'];
	}
	| {
		method: 'delete';
		path: `/auth/mfa/totp`;
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/onboard/hello`;
		parts: 2;
		params: undefined;
		response: operations['hello_hello']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: `/onboard/complete`;
		parts: 2;
		params: operations['complete_complete']['requestBody']['content'][
			'application/json'
		];
		response: operations['complete_complete']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: `/push/subscribe`;
		parts: 2;
		params: operations['subscribe_subscribe']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'post';
		path: `/push/unsubscribe`;
		parts: 2;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/sync/settings/fetch`;
		parts: 3;
		params: operations['get_settings_fetch']['requestBody']['content'][
			'application/json'
		];
		response: operations['get_settings_fetch']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: `/sync/settings/set`;
		parts: 3;
		params:
			| operations['set_settings_set']['parameters']['query']
			| operations['set_settings_set']['requestBody']['content'][
				'application/json'
			];
		response: undefined;
	}
	| {
		method: 'get';
		path: `/sync/unreads`;
		parts: 2;
		params: undefined;
		response: operations['get_unreads_unreads']['responses']['200']['content'][
			'application/json'
		];
	};
