name: Build

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # auth w/JSR
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.2
      - name: publish to jsr
        run: deno publish
